kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: rhdh
data:
  "app-config-rhdh.yaml": |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh.${DOMAIN}
    backend:
      auth:
        keys:
          - secret: "${BACKEND_SECRET}"
      baseUrl: https://backstage-developer-hub-rhdh.${DOMAIN}
      cors:
        origin: https://backstage-developer-hub-rhdh.${DOMAIN}
    integrations:
      github:
        - host: github.com
          token:  ${GITHUB_TOKEN}
          apps:
            - appId: ${GITHUB_APP_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY}
    # signInPage: bitbucket
    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      environment: development
      providers:
        github:
          development:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        guest: 
          dangerouslyAllowOutsideDevelopment: true

    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, Group, User, Resource, Location, Template, API]
      locations:
        - type: url
          target: https://github.com/AndrienkoAleksandr/catalog-model/blob/rbac/examples/all.yaml
        - type: url
          target: https://github.com/AndrienkoAleksandr/catalog-model/blob/rbac/examples/acme-corp.yaml
          rules:
            - allow: [User, Group]

    # Plugin: Permission
    permission:
      enabled: false
      rbac:
        pluginsWithPermission:
          - catalog
          - permission
          - scaffolder
        admin:
          users:
          # superUsers:
            - name: ${RBAC_ADMIN_USER}
