apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh
spec:
  deployment:
    patch:
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: backstage-backend
                image: {IMAGE}
            initContainers:
              - name: install-dynamic-plugins
                image: {IMAGE}
      name: install-dynamic-plugins
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
         - name: app-config-rhdh
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraEnvs:
      envs:
      - name: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      secrets:
         - name: secrets-rhdh
    extraFiles:
      mountPath: /opt/app-root/src
    route:
      enabled: true
  database:
    enableLocalDb: true
