kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
  namespace: rhdh
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
        disabled: true
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage-community.plugin-rbac:
                appIcons:
                  - name: rbacIcon
                    importName: RbacIcon
                dynamicRoutes:
                  - path: /rbac
                    importName: RbacPage
                    menuItem:
                      icon: rbacIcon
                      text: RBAC
                menuItems:
                  rbac:
                    parent: admin
                    icon: rbacIcon

      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
        disabled: false
      - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-dynamic-home-page
        disabled: false
